edit docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -15,6 +15,10 @@ on:
         required: false
         type: string
         default: pinjammodal/node:12.22.9-3.14
+      env_file:
+        description: 'Use to load environment variable from file'
+        required: false
+        type: string
       strict_scan:
         required: false
         type: string
@@ -38,9 +42,40 @@ env:
   STRICT_SCAN: ${{ inputs.strict_scan || false }}
 
 jobs:
-  build-push:
-    needs: [define]
+  define:
     runs-on: ubuntu-latest
+
+    outputs:
+      continueOnError: ${{ steps.strictScan.outputs.continueOnError }}
+      runner: ${{ steps.runner.outputs.value }}
+
+    steps:
+      - id: strictScan
+        run: |
+          if ${{ inputs.strict_scan == 'false'}}
+          then
+            echo "::set-output name=continueOnError::${{ toJSON(true) }}"
+            echo "::notice title=continueOnError::true"
+          else
+            echo "::set-output name=continueOnError::${{ toJSON(false) }}"
+            echo "::notice title=continueOnError::false"
+          fi
+      - id: runner
+        run: |
+          if ${{startsWith(inputs.docker_context, 'PM')}}
+          then
+            echo "::set-output name=value::fit-runner-1"
+            echo "::notice title=runner::fit-runner-1"
+          elif ${{startsWith(inputs.docker_context, 'DMS')}}
+          then
+            echo "::set-output name=value::dms-runner-1"
+            echo "::notice title=runner::dms-runner-1"
+          fi
+
+
+  build:
+    needs: [define]
+    runs-on: [self-hosted]
 
     outputs:
       imageTag: ${{ steps.meta.outputs.tags }}
@@ -55,7 +90,7 @@ jobs:
 
       - name: Docker Meta
         id: meta
-        run: echo "tags=pinjammodal/${{ env.SERVICE_NAME }}:${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
+        run: echo "::set-output name=tags::pinjammodal/${{ env.SERVICE_NAME }}:${GITHUB_REF#refs/*/}" 
 
       - name: Notice meta
         run: echo "::notice title=meta tag created::${{ steps.meta.outputs.tags }}"
@@ -64,7 +99,7 @@ jobs:
         run: docker context use default
 
       - name: Login to Docker Hub
-        uses: docker/login-action@v2.1.0
+        uses: docker/login-action@v2.0.0
         with:
           username: ${{ secrets.cr_username }} 
           password: ${{ secrets.cr_token }}
@@ -74,28 +109,57 @@ jobs:
         run: source ${{ inputs.env_file }}
 
       - name: Build Docker
-        uses: docker/build-push-action@v3.2.0
+        uses: docker/build-push-action@v3.1.1
         with:
           context: .
           outputs: type=docker
           tags: ${{ steps.meta.outputs.tags }}
           build-args: |
             NODE_BASE=${{ inputs.node_base_image }}
+
+  container-scan:
+    needs: [define, build]
+    runs-on: [self-hosted]
     
+    steps:
       - run: docker context use default
 
       - name: Login to Container Registry
-        run: docker login -u ${{ secrets.cr_username }} -p ${{ secrets.cr_token }}
+        run: |
+          docker context use default
+          docker login -u ${{ secrets.cr_username }} -p ${{ secrets.cr_token }}
 
+      # - run: docker pull ${{ needs.build.outputs.imageTag }}
+
+      - name: Run Snyk to check Docker image for vulnerabilities
+        uses: snyk/actions/docker@master
+        env:
+          SNYK_TOKEN: ${{ secrets.snyk_token }}
+        with:
+          image: ${{ needs.build.outputs.imageTag }}
+          args: --severity-threshold=high
+          command: test
+
+  push:
+    needs: [define, build, container-scan]
+    runs-on: [self-hosted]
+
+    steps:
       - name: Check Build Result
         run: |
           docker images | grep ${{ env.SERVICE_NAME }} > tmp_docker
           if grep -wq ${GITHUB_REF#refs/*/} tmp_docker; then echo "::notice title=image build verified::${{ steps.meta.outputs.tags }} image found" ; else echo "::error title=build error::${{ steps.meta.outputs.tags }} not found"; fi
 
       - name: Push Docker Image to Container Registry
-        run: docker push ${{ steps.meta.outputs.tags }}
+        run: docker push ${{ needs.build.outputs.imageTag }}
 
-      - name: runner image cleanup
+  runner-cleanup:
+    needs: [define, push]
+    runs-on: [self-hosted]
+
+    steps:
+      - name: Prune Images
         run: |
           docker context use default
-          docker image rm -f ${{ steps.meta.outputs.tags }}
+          docker image prune -a -f
+          docker rmi -f $(docker images -f "dangling=true" -q) || true
